name: Checkov Scan

on:
  workflow_dispatch:  # Allows manual execution
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

jobs:
  checkov-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Pulls the repo
        with:
          repository: kratarget/team1
          ref: main
          token: ${{ secrets.PACKAGES_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform