name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs on push to main branch
  workflow_dispatch:  # Allows manual execution

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Uses GitHub-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Pulls the repo

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/team1-app:latest .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository }}/team1-app:latest
