name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs on push to main branch
  workflow_dispatch:  # Allows manual execution

env:
  REGISTRY: oneretailhackaton.jfrog.io/virtual-docker
  IMAGE_NAME: oneretailhackaton.jfrog.io/virtual-docker/oneretail-app:${{ github.run_number }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Uses GitHub-hosted runner

    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Pulls the repo
        with:
          repository: kratarget/team1
          ref: main
          token: ${{ secrets.PACKAGES_TOKEN }}

      - name: Set up JDK 17  # Change this version if needed
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build the project with Maven
        run: mvn clean package -DskipTests  # Add -DskipTests if you want to skip tests

      - name: Bump Maven version
        run: |
          VERSION="1.0.${{ github.run_number }}"
          echo "Updating Maven project to version: $VERSION"
          mvn versions:set -DnewVersion=$VERSION

      - name: maven build
        run: |
              jf mvn-config --repo-deploy-releases=${ARTIFACTORY_RELEASE} --repo-deploy-snapshots=${ARTIFACTORY_SNAPSHOT}
              jf mvn deploy
              jf rt bp oneretail-app ${{ github.run_number }}

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Deploy to JFrog Artifactory
        run: jfrog rt upload "**/*.jar" "team1-libs-snapshot"
        env:
         JF_URL: ${{ vars.JF_URL }}
         JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}}

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.PACKAGES_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/oneretail-app:${{ github.run_number }} .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository }}/oneretail-app:${{ github.run_number }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: oneretailhackaton.jfrog.io/virtual-docker
          username: tahar.sayagh@external.engie.com
          password: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: "./app"
          file: "./Dockerfile"
          push: true
          tags: ${{ env.IMAGE_NAME }}
