name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs on push to main branch
  workflow_dispatch:  # Allows manual execution

# Define environment variables, including the Artifactory repo names:
env:
  ARTIFACTORY_RELEASE: team1-libs-release    # <-- Change to your release repo name
  ARTIFACTORY_SNAPSHOT: team1-libs-snapshot  # <-- Change to your snapshot repo name
  REGISTRY: oneretailhackaton.jfrog.io/virtual-docker
  IMAGE_NAME: oneretailhackaton.jfrog.io/virtual-docker/oneretail-app:${{ github.run_number }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Uses GitHub-hosted runner

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # If your code is in the same repo, you normally only need:
          #   uses: actions/checkout@v4
          # If it's in another repo (kratarget/team1), specify it:
          repository: kratarget/team1
          ref: main
          token: ${{ secrets.PACKAGES_TOKEN }}

      - name: Set up Java (Maven)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # --------------------------------------------------------
      # 1) Install & configure JFrog CLI BEFORE using "jf" commands
      # --------------------------------------------------------
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: 'latest'
        env:
          # If you have these in GitHub "Actions Variables" or "Secrets and variables"
          JF_URL: ${{ vars.JF_URL }}               # e.g. https://mycompany.jfrog.io (no trailing /artifactory)
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Configure a Server ID
        run: |
          jf c add my-jfrog-server \
            --interactive=false \
            --artifactory-url="${{ env.JF_URL }}" \
            --access-token="${{ env.JF_ACCESS_TOKEN }}"

          jf c use my-jfrog-server

      - name: Maven deploy to Artifactory with JFrog CLI
        run: |
          VERSION="1.0.${{ github.run_number }}"
          echo "Updating Maven project to version: $VERSION"
          mvn versions:set -DnewVersion=$VERSION
          
          # Configure which repositories to use for snapshots/releases:
          jf mvn-config \
             --repo-deploy-releases=${ARTIFACTORY_RELEASE} \
             --repo-deploy-snapshots=${ARTIFACTORY_SNAPSHOT}

          # Deploy using JFrog CLI:
          jf mvn deploy

          # (Optional) Publish build info to Artifactory:
          jf rt bp oneretail-app ${{ github.run_number }}

      - name: Upload JAR to Artifactory (optional extra step)
        run: |
          # Example of uploading all .jar files to the snapshot repo:
          jf rt upload "**/*.jar" "${{ env.ARTIFACTORY_SNAPSHOT }}"
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      # --------------------------------------------------------
      # 3) Push Docker image to GHCR (GitHub Container Registry)
      # --------------------------------------------------------
      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.PACKAGES_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image for GHCR
        run: docker build -t ghcr.io/${{ github.repository }}/oneretail-app:${{ github.run_number }} .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository }}/oneretail-app:${{ github.run_number }}

      # --------------------------------------------------------
      # 4) Push Docker image to JFrog Artifactory Docker registry
      # --------------------------------------------------------
      - name: Log in to the JFrog Docker registry
        uses: docker/login-action@v3
        with:
          registry: oneretailhackaton.jfrog.io/virtual-docker
          username: "tahar.sayagh@gexternal.engie.com" # or an Artifactory username if needed
          password: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and push Docker image to Artifactory
        id: push
        uses: docker/build-push-action@v6
        with:
          # If your Dockerfile is in the root directory:
          #   context: .
          #   file: ./Dockerfile
          # If it's in an "app" subfolder, adjust accordingly
          context: "./app"
          file: "./Dockerfile"
          push: true
          tags: ${{ env.IMAGE_NAME }}
